eureka:
  client:
    register-with-eureka: false

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/student/**

        - id: school
          uri: http://localhost:8070
          predicates:
            - Path=/school/**

server:
  port: 8222
